const { test, expect } = require('@playwright/test');

test('pesquisa e comunicado: API autenticada, resposta publica e anexos', async ({ page, browser }) => {
  await page.goto('/login');
  await page.getByLabel('Usuário').fill('browser.owner@example.com');
  await page.getByLabel('Senha').fill('Browser-Teste-123');
  await page.getByRole('button', { name: 'Entrar no sistema' }).click();
  await expect(page).toHaveURL(/\/app$/);
  const bootstrap = await (await page.request.get('/api/bootstrap')).json();
  const headers = { 'X-CSRF-Token': bootstrap.csrfToken };
  const save = await page.request.post('/api/data', { headers, data: { key: 'state', value: { satisfaction: { qps_sat_form: { versoes: [{ versao: '01', status: 'Vigente', perguntas: [{ id: 'q1', texto: 'Como foi o atendimento?', tipo: 'escala' }] }] } } } } });
  expect(save.ok()).toBeTruthy();
  const surveyResponse = await page.request.post('/api/external-feedback-requests?kind=survey', { headers, data: { id: 'browser-survey', empresa: 'Teste isolado', email: 'test@example.test', formVersao: '01' } });
  expect(surveyResponse.ok()).toBeTruthy();
  const survey = await surveyResponse.json();
  expect(survey.delivery).toBe('not_configured');
  expect(survey.record.status).toBe('Envio pendente');
  const context = await browser.newContext();
  const recipient = await context.newPage();
  const errors = [];
  recipient.on('pageerror', error => errors.push(error.message));
  await recipient.goto(survey.link);
  await recipient.getByLabel('Como foi o atendimento?').selectOption('9');
  await recipient.getByRole('button', { name: 'Enviar resposta' }).click();
  await expect(recipient.getByText('Resposta enviada com sucesso. Obrigado!')).toBeVisible();
  const rows = await (await page.request.get('/api/external-feedback-requests?kind=survey')).json();
  expect(rows.records[0].respostas.q1).toBe(9);
  const supplierResponse = await page.request.post('/api/external-feedback-requests?kind=supplier', { headers, data: { id: 'browser-supplier', email: 'supplier@example.test', fornNome: 'Fornecedor teste', descricao: 'Corrigir entrega', anexos: [{ name: 'evidencia.txt', content: Buffer.from('Evidencia de teste').toString('base64') }] } });
  expect(supplierResponse.ok()).toBeTruthy();
  const supplier = await supplierResponse.json();
  await recipient.setViewportSize({ width: 390, height: 844 });
  await recipient.goto(supplier.link);
  const downloadPromise = recipient.waitForEvent('download');
  await recipient.getByRole('button', { name: 'Baixar evidencia.txt' }).click();
  expect((await downloadPromise).suggestedFilename()).toBe('evidencia.txt');
  await recipient.getByLabel('Ações tomadas e considerações').fill('Entrega corrigida para o teste.');
  await recipient.getByLabel('Evidências').setInputFiles({ name: 'retorno.txt', mimeType: 'text/plain', buffer: Buffer.from('Correcao comprovada') });
  await recipient.getByRole('button', { name: 'Enviar resposta' }).click();
  await expect(recipient.getByText('Resposta enviada com sucesso. Obrigado!')).toBeVisible();
  const review = await page.request.patch('/api/external-feedback-requests?kind=supplier', { headers, data: { id: 'browser-supplier', verdict: 'Procedente' } });
  expect(review.ok()).toBeTruthy();
  expect((await review.json()).record.statusRetorno).toBe('Procedente');
  const unauthorized = await context.request.get('/api/external-feedback-requests?kind=supplier');
  expect(unauthorized.status()).toBe(401);
  expect(errors).toEqual([]);
  await page.request.delete('/api/external-feedback-requests?kind=survey', { headers, data: { id: 'browser-survey' } });
  await page.request.delete('/api/external-feedback-requests?kind=supplier', { headers, data: { id: 'browser-supplier' } });
  await page.request.post('/api/data', { headers, data: { key: 'state', value: bootstrap.state || {} } });
  await context.close();
});

test('botoes dos modulos salvam envio pendente sem simular sucesso', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('Usuário').fill('browser.owner@example.com');
  await page.getByLabel('Senha').fill('Browser-Teste-123');
  await page.getByRole('button', { name: 'Entrar no sistema' }).click();
  await expect(page).toHaveURL(/\/app$/);
  const bootstrap = await (await page.request.get('/api/bootstrap')).json();
  const headers = { 'X-CSRF-Token': bootstrap.csrfToken };
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.request.post('/api/data', { headers, data: { key: 'state', value: { ...(bootstrap.state || {}), satisfaction: { qps_sat_form: { versoes: [{ versao: '01', status: 'Vigente', perguntas: [{ id: 'q1', texto: 'Atendimento', tipo: 'escala' }] }] } } } } });
  await page.reload();
  await page.evaluate(() => renderModuleDetail('satisfacao-clientes'));
  let frame = page.frameLocator('.page-content iframe').first();
  await frame.locator('[data-tab="envio"]').click();
  await frame.locator('#envCliente').selectOption('__manual');
  await frame.locator('#envResponsavel').fill('Contato teste');
  await frame.locator('#envEmail').fill('survey@example.test');
  await frame.locator('#envCnpj').fill('00.000.000/0001-00');
  await frame.locator('#envEmpresa').fill('Cliente teste');
  await frame.getByText('Enviar pesquisa', { exact: true }).click();
  await expect(frame.getByText('Pesquisa salva, mas o e-mail não foi enviado.', { exact: false })).toBeVisible();
  await page.evaluate(() => renderModuleDetail('fornecedores'));
  frame = page.frameLocator('.page-content iframe').first();
  await frame.locator('[data-tab="acoes"]').click();
  await frame.getByText('Nova ação', { exact: true }).click();
  await frame.locator('#acEmail').fill('supplier@example.test');
  await frame.locator('#acDescricao').fill('Comunicado de teste da interface');
  await frame.getByText('Enviar ao fornecedor', { exact: true }).click();
  await expect(frame.getByText('Comunicado salvo, mas o e-mail não foi enviado.', { exact: false })).toBeVisible();
  expect(errors).toEqual([]);
  for (const kind of ['survey', 'supplier']) {
    const { records } = await (await page.request.get(`/api/external-feedback-requests?kind=${kind}`)).json();
    for (const record of records) await page.request.delete(`/api/external-feedback-requests?kind=${kind}`, { headers, data: { id: record.id } });
  }
  await page.request.post('/api/data', { headers, data: { key: 'state', value: bootstrap.state || {} } });
});
