const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
Object.assign(process.env, { SGQ_DATABASE_MODE: 'local', SGQ_DATA_DIR: fs.mkdtempSync(path.join(os.tmpdir(), 'sgq-feedback-test-')), SGQ_ADMIN_USER: 'unused-admin', SGQ_EXTRA_LOGINS: '' });
const db = require('../db');
const { createExternalFeedback } = require('../external-feedback');

test('external feedback: delivery, retries, reminders, answers, evidence, review and revocation', async () => {
  const company = await db.createCompany({ name: 'Isolated feedback test' });
  let time = Date.now();
  let status = 'failed';
  const messages = [];
  const service = createExternalFeedback({ secret: 'isolated-test-secret', appUrl: 'https://example.test', now: () => time, sendEmail: async message => { messages.push(message); return { status, id: 'test-message' }; } });
  const requester = { email: 'owner@example.test' };
  await db.mutateSupplierData(company.id, data => {
    data.state = { satisfaction: { qps_sat_form: { versoes: [{ versao: '01', status: 'Vigente', perguntas: [{ id: 'q1', tipo: 'escala', texto: 'Nota' }, { id: 'q2', tipo: 'texto', texto: 'Comentario' }] }] } } };
  });
  const survey = { id: 'survey-test', email: 'client@example.test', empresa: 'Client', formVersao: '01' };
  const first = await service.request(company.id, 'survey', survey, requester);
  assert.equal(first.record.status, 'Envio pendente');
  const token = new URL(first.link).hash.slice(1);
  await assert.rejects(service.read(token + 'bad'), { status: 401 });
  await assert.rejects(service.request(company.id, 'survey', { ...survey, id: 'invalid', formVersao: '02' }, requester), { status: 409 });
  status = 'sent';
  const retry = await service.request(company.id, 'survey', survey, requester);
  assert.equal(retry.record.status, 'Enviada');
  assert.equal((await service.list(company.id, 'survey')).length, 1);
  time += 7 * 86400000;
  await Promise.all([service.deliver(company.id), service.deliver(company.id)]);
  assert.equal(messages.filter(m => m.tag.endsWith('reminder')).length, 1);
  await assert.rejects(service.respond(token, { answers: { q1: 3.5 } }), { status: 400 });
  status = 'failed';
  await service.respond(token, { answers: { q1: 3, q2: 'Feedback' } });
  assert.equal((await service.list(company.id, 'survey'))[0].status, 'Respondida');
  await assert.rejects(service.respond(token, { answers: { q1: 8 } }), { status: 409 });
  status = 'sent';
  await service.deliver(company.id);
  const mailCount = messages.length;
  await service.deliver(company.id);
  assert.equal(messages.length, mailCount);
  const attachment = { name: 'evidence.txt', content: Buffer.from('Evidence').toString('base64') };
  const supplier = await service.request(company.id, 'supplier', { id: 'supplier-test', email: 'vendor@example.test', descricao: 'Correct the delivery', anexos: [attachment] }, requester);
  const supplierToken = new URL(supplier.link).hash.slice(1);
  assert.equal((await service.download(supplierToken, 0)).content, attachment.content);
  await assert.rejects(service.download(token, 0), { status: 404 });
  await assert.rejects(service.respond(supplierToken, { actions: '', files: [] }), { status: 400 });
  await service.respond(supplierToken, { actions: 'Corrected', files: [attachment] });
  await service.update(company.id, 'supplier', { id: 'supplier-test', verdict: 'Procedente' });
  assert.equal((await service.list(company.id, 'supplier'))[0].statusRetorno, 'Procedente');
  assert.equal((await service.list(company.id, 'supplier'))[0].resposta.anexos[0].content, attachment.content);
  await service.update(company.id, 'survey', { id: survey.id }, true);
  await assert.rejects(service.read(token), { status: 410 });
  await db.mutateSupplierData(company.id, data => {
    data.state.satisfaction.qps_sat_pesquisas = [survey];
    service.mergeSurveys(data);
    assert.equal(data.state.satisfaction.qps_sat_pesquisas.length, 0);
  });
  time += 91 * 86400000;
  await assert.rejects(service.read(supplierToken), { status: 410 });
});
