const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const http = require("node:http");

const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "sgq-supplier-test-"));
Object.assign(process.env, { SGQ_DATABASE_MODE: "local", SGQ_DATA_DIR: dataDir, SGQ_LOGIN_USER: "supplier.owner@example.com", SGQ_USER_PASSWORD: "Supplier-Test-123", SGQ_COMPANY_NAME: "Supplier Test", SGQ_ADMIN_USER: "unused-admin", SGQ_EXTRA_LOGINS: "", SESSION_SECRET: "supplier-test-secret-long-and-isolated", RESEND_API_KEY: "", EMAIL_FROM: "", PUBLIC_APP_URL: "https://sgq.example.test" });
const db = require("../db");
const { createSupplierRnc } = require("../supplier-rnc");

test("supplier portal isolates RNCs, persists evidence, handles concurrency and seven-day reminders", async (t) => {
  let time = Date.now();
  const mail = [];
  const service = createSupplierRnc({ secret: process.env.SESSION_SECRET, appUrl: process.env.PUBLIC_APP_URL, now: () => time, sendEmail: async (message) => { mail.push(message); return { status: "sent" }; } });
  await db.syncConfiguredUsers([{ user: process.env.SGQ_LOGIN_USER, password: process.env.SGQ_USER_PASSWORD, companyName: "Supplier Test" }]);
  const user = await db.findUser(process.env.SGQ_LOGIN_USER, process.env.SGQ_USER_PASSWORD);
  const companyId = user.companyId;
  const ncPhoto = { id: "8cb3642b-0d42-4781-b976-ae8eb7d1b062", name: "evidencia-rnc.png", size: 68, type: "image/png" };
  const makeRow = (id) => ({ id, origem: "Fornecedor", origemRef: "Fornecedor Teste", fornecedorEmail: "vendor@example.test", descricao: "Peça fora de especificação", status: "Aguardando análise", ishikawa: {}, acoes: [], evidencias: id === "RNC-A" ? [ncPhoto] : [], historico: [] });
  await db.mutateSupplierData(companyId, (data) => service.prepareState(data, { ncs: [makeRow("RNC-A"), makeRow("RNC-B")], users: [{ secret: "not-public" }], documents: [{ id: "secret-document" }] }, true));
  await db.setCompanyData(companyId, `ncAttachment:${ncPhoto.id}`, { ...ncPhoto, base64: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAF/gJ+NQdFlAAAAABJRU5ErkJggg==" });
  await Promise.all([service.deliver(companyId), service.deliver(companyId)]);
  assert.equal(mail.length, 2);
  const tokenFor = (index) => new URL(mail[index].html.match(/href="([^"]+)"/)[1]).hash.slice(1);
  const tokenA = tokenFor(0);
  const tokenB = tokenFor(1);
  const initial = await service.read(tokenA);
  assert.equal(initial.id, "RNC-A");
  assert.deepEqual(initial.ncEvidences, [ncPhoto]);
  assert.ok(Object.values(initial.ishikawa).every((value) => value === ""));
  assert.equal(initial.users, undefined);
  assert.equal(initial.documents, undefined);
  await assert.rejects(service.read(`${tokenA.slice(0, -5)}WRONG`), { status: 401 });
  const evidence = await service.upload(tokenA, { name: "evidência.txt", base64: Buffer.from("Evidencia real da acao").toString("base64") });
  assert.equal(Buffer.from((await service.download(tokenA, evidence.id)).base64, "base64").toString(), "Evidencia real da acao");
  await assert.rejects(service.download(tokenB, evidence.id), { status: 404 });
  assert.equal((await service.downloadNcEvidence(tokenA, ncPhoto.id)).name, ncPhoto.name);
  await assert.rejects(service.downloadNcEvidence(tokenB, ncPhoto.id), { status: 404 });
  await assert.rejects(service.upload(tokenA, { name: "attack.html", base64: "YWJj" }), { status: 400 });
  await assert.rejects(service.respond(tokenA, { version: initial.version, ishikawa: {}, acoes: [], companyId: 99 }), { status: 400 });
  const stale = structuredClone(await db.getCompanyData(companyId, "state"));
  const response = await service.respond(tokenA, { version: initial.version, ishikawa: { metodo: "Procedimento revisado" }, acoes: [{ desc: "Revisar o procedimento", prazo: "Em dez dias", responsavel: "Equipe externa", status: "Em validação no fornecedor", evidenceIds: [evidence.id] }] });
  assert.equal(response.acoes[0].status, "Em validação no fornecedor");
  assert.equal(response.acoes[0].evidenceIds[0], evidence.id);
  assert.ok(response.respondedAt);
  assert.equal((await db.getCompanyData(companyId, "state")).ncs[0].ishikawa.metodo, "Procedimento revisado");
  await assert.rejects(db.mutateSupplierData(companyId, (data) => service.prepareState(data, stale, true)), { status: 409 });
  await assert.rejects(service.respond(tokenA, { version: initial.version, ishikawa: { metodo: "Desatualizado" }, acoes: [] }), { status: 409 });
  time += 7 * 86400000 - 1;
  await service.runNotifications();
  assert.equal(mail.length, 2);
  time += 2;
  await service.runNotifications();
  assert.equal(mail.length, 3);
  assert.match(mail[2].subject, /RNC-B/);
  assert.match(mail[2].html, /pontuação.*fins comerciais/);
  await service.runNotifications();
  assert.equal(mail.length, 3);

  const server = http.createServer(require("../server"));
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  t.after(() => { server.closeAllConnections(); return new Promise((resolve) => server.close(resolve)); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const headers = { Authorization: `Bearer ${tokenA}` };
  assert.equal((await fetch(`${base}/api/supplier-rnc`, { headers })).status, 200);
  assert.equal((await fetch(`${base}/api/bootstrap`, { headers })).status, 401);
  assert.equal((await fetch(`${base}/api/nc-evidence?nc=RNC-A&file=${evidence.id}`, { headers })).status, 401);
  assert.equal((await fetch(`${base}/api/data`, { method: "POST", headers: { ...headers, "Content-Type": "application/json" }, body: JSON.stringify({ key: "state", value: { ncs: [] } }) })).status, 401);
  assert.equal((await fetch(`${base}/api/supplier-rnc/evidence/${evidence.id}`, { headers })).status, 200);
  const ncPhotoResponse = await fetch(`${base}/api/supplier-rnc/nc-evidence/${ncPhoto.id}`, { headers });
  assert.equal(ncPhotoResponse.status, 200);
  assert.equal(ncPhotoResponse.headers.get("content-type"), "image/png");
  assert.equal(ncPhotoResponse.headers.get("content-disposition").startsWith("inline"), true);
  assert.equal((await fetch(`${base}/api/supplier-rnc/nc-evidence/${ncPhoto.id}`, { headers: { Authorization: `Bearer ${tokenB}` } })).status, 404);
  const page = await fetch(`${base}/supplier-rnc`);
  assert.equal(page.headers.get("referrer-policy"), "no-referrer");
  assert.match(await page.text(), /Análise da causa/);
  assert.equal((await fetch(`${base}/api/supplier-rnc`, { method: "POST", headers: { ...headers, "Content-Type": "application/json" }, body: JSON.stringify({ ...response, companyId: 99 }) })).status, 400);

  const login = await fetch(`${base}/login`, { method: "POST", redirect: "manual", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ username: process.env.SGQ_LOGIN_USER, password: process.env.SGQ_USER_PASSWORD }) });
  assert.equal(login.status, 302);
  const cookie = login.headers.get("set-cookie").split(";")[0];
  const bootstrap = await (await fetch(`${base}/api/bootstrap`, { headers: { Cookie: cookie } })).json();
  assert.equal(bootstrap.state.supplierRncPrivate, undefined);
  const createState = structuredClone(bootstrap.state);
  createState.ncs.push(makeRow("RNC-C"));
  const saved = await fetch(`${base}/api/data`, { method: "POST", headers: { Cookie: cookie, "X-CSRF-Token": bootstrap.csrfToken, "Content-Type": "application/json" }, body: JSON.stringify({ key: "state", moduleId: "nao-conformidades", value: createState }) });
  assert.equal(saved.status, 200);
  const savedBody = await saved.json();
  assert.equal(savedBody.supplierDeliveries.find((item) => item.ncId === "RNC-C").status, "not_configured");
  assert.equal(savedBody.ncs.length, 3);
  const internalFile = await fetch(`${base}/api/nc-evidence?nc=RNC-A&file=${evidence.id}`, { headers: { Cookie: cookie } });
  assert.equal(internalFile.status, 200);
  assert.equal(await internalFile.text(), "Evidencia real da acao");
  assert.equal((await fetch(`${base}/api/nc-evidence?nc=RNC-B&file=${evidence.id}`, { headers: { Cookie: cookie } })).status, 404);
  const changedEmailState = structuredClone(savedBody.ncs);
  changedEmailState.find((item) => item.id === "RNC-B").fornecedorEmail = "new-vendor@example.test";
  await db.mutateSupplierData(companyId, (data) => service.prepareState(data, { ...data.state, ncs: changedEmailState }, true));
  await assert.rejects(service.read(tokenB), { status: 410 });

  const current = structuredClone(await db.getCompanyData(companyId, "state"));
  current.ncs[0].encerradoEm = "2026-09-02";
  await db.mutateSupplierData(companyId, (data) => service.prepareState(data, current, true));
  await assert.rejects(service.read(tokenA), { status: 410 });
  time += 91 * 86400000;
  await assert.rejects(service.read(tokenB), { status: 410 });
});

test("failed email delivery stays pending and is retried without duplicating saved RNC", async () => {
  const company = await db.ensureCompany("Supplier Delivery Failure");
  let fail = true;
  let attempts = 0;
  const service = createSupplierRnc({ secret: process.env.SESSION_SECRET, appUrl: process.env.PUBLIC_APP_URL, sendEmail: async (message) => { if (message.subject.includes("RNC-FAIL")) attempts++; return { status: fail ? "failed" : "sent" }; } });
  await db.mutateSupplierData(company.id, (data) => service.prepareState(data, { ncs: [{ id: "RNC-FAIL", origem: "Fornecedor", fornecedorEmail: "vendor@example.test" }] }, true));
  assert.equal((await service.deliver(company.id))[0].status, "failed");
  assert.equal((await db.getCompanyData(company.id, "state")).ncs.length, 1);
  fail = false;
  await service.runNotifications();
  assert.equal((await db.getCompanyData(company.id, "supplierRncPrivate")).entries[0].deliveryStatus, "sent");
  await service.deliver(company.id);
  assert.equal(attempts, 2);
});

test.after(() => fs.rmSync(dataDir, { recursive: true, force: true }));
